Fix Azimuth Docker build: install Bioconductor deps before satijalab/azimuth
The satijalab/azimuth install_github silently failed in the first build with
  ERROR: dependencies 'BSgenome.Hsapiens.UCSC.hg38', 'EnsDb.Hsapiens.v86',
  'glmGamPoi', 'Signac', 'TFBSTools' are not available for package 'Azimuth'
which left the Azimuth package unbuilt and the smoke-test step failed with
'there is no package called Azimuth'. Add a BiocManager::install step for the
5 missing Bioconductor packages prior to the GitHub install. Also add libuv1-dev
to the apt-get list to satisfy a configure-time warning from one of the R deps.